apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: localstack
  namespace: nslocalstack
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: nginx
  rules:
    - host: midominio.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: localstack
                port:
                  number: 4566